CREATE TABLE CLIENTE (
	CODIGO INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	NOMBRE VARCHAR(40) NOT NULL,
	TIPO_DOCUMENTO_DE_IDENTIFICACION VARCHAR(3) NOT NULL,
	NUMERO_DOCUMENTO_DE_IDENTIFICACION INT NOT NULL,
	NOMBRE_DEL_REPRESENTANTE_LEGAL VARCHAR(40) NOT NULL,
	TELEFONOS VARCHAR(12),
	EMAIL VARCHAR(40),
	PERSONA_DE_CONTACTO VARCHAR(40),
	VALOR_ACTIVOS FLOAT,
	VALOR_PASIVOS FLOAT,
	VALOR_PATRIMONIO FLOAT
);